# Copyright 2026 Antigravity
# Description: SConscript for CVA6RtlCPU.

Import('*')

SimObject('CVA6RtlCPU.py', sim_objects=['CVA6RtlCPU'])
Source('cva6_rtl_cpu.cc')

# Append Verilator compile flags and library paths to the SCons environment
env.Append(CPPDEFINES=['VM_TRACE=1'])
env.Append(CPPPATH=[
    '/home/julian/gem5_cva6/cva6/work-ver-core',
    '/usr/local/share/verilator/include',
    '/usr/local/share/verilator/include/vltstd'
])

env.Append(LIBPATH=[
    '/home/julian/gem5_cva6/cva6/work-ver-core'
])

env.Append(LIBS=[
    'Vcva6_top',
    'verilated'
])
